apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-worker
  labels:
    app: edge-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-worker
  template:
    metadata:
      labels:
        app: edge-worker
    spec:
      containers:
      - name: edge-worker
        image: mfatihaktas/edge-load-balance
        ports:
        - containerPort: 5000
        command: ["python3", "-u"]
        args: ["/home/app/worker.py"]

---

apiVersion: v1
kind: Service
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  clusterIP: None
  selector:
    app: edge-worker

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-master
  labels:
    app: edge-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-master
  template:
    metadata:
      labels:
        app: edge-master
    spec:
      containers:
      - name: edge-master
        image: mfatihaktas/edge-load-balance
        ports:
        - containerPort: 5000
        command: ["python3", "-u"]
        args: ["/home/app/master.py"]

---

apiVersion: v1
kind: Service
metadata:
  name: edge-nodeport
spec:
  selector:
    app: edge-master
  type: NodePort
  ports:
  - name: tcp
    port: 5000
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
