apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-worker
  labels:
    app: edge-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-worker
  template:
    metadata:
      labels:
        app: edge-worker
    spec:
      containers:
      - name: edge-worker
        image: mfatihaktas/edge-load-balance
        ports:
        - containerPort: 5000
        command: ["python3", "-u"]
        args: ["/home/app/worker.py"]
