apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
  - name: udp
    protocol: UDP
    port: 5000
    targetPort: 5000
    nodePort: 30000
  selector:
    app: nginx
