apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
#   labels:
#     app: hello-world
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     ports:
#       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer # NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30000