apiVersion: v1
kind: Service
metadata:
  name: edge-nodeport
spec:
  selector:
    app: edge-master
  type: NodePort
  ports:
  - name: tcp
    port: 5000
    targetPort: 5000
    nodePort: 30000
    protocol: TCP
