apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-master
  labels:
    app: edge-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-master
  template:
    metadata:
      labels:
        app: edge-master
    spec:
      containers:
      - name: edge-master
        image: mfatihaktas/edge-load-balance
        ports:
        - containerPort: 5000
