apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf
  labels:
    app: iperf
spec:
  selector:
    matchLabels:
      app: iperf
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf
    spec:
      containers:
      - name: iperf
        image: networkstatic/iperf3
        args: ["-s", "-p", "5000"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: iperf
spec:
  type: LoadBalancer
  selector:
    app: iperf
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000
      nodePort: 30000